# Generated by Django 5.0.9 on 2024-09-15 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tempe', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PesananTempe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal_pesanan', models.DateTimeField(auto_now_add=True)),
                ('alamat_pengiriman', models.CharField(max_length=255)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tempe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tempe')),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pengiriman', models.CharField(max_length=50)),
                ('tanggal_pengiriman', models.DateTimeField(blank=True, null=True)),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pesanantempe')),
            ],
        ),
    ]
