# Generated by Django 5.0.9 on 2024-09-23 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.IntegerField()),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PengirimanProduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat_pengiriman', models.CharField(max_length=255)),
                ('tanggal_pengiriman', models.DateField()),
                ('jumlah', models.IntegerField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produk')),
            ],
        ),
    ]
